### ISSUE TITLE
bin/console kahlan:run not registered in symfony4 and kahlan4

### ISSUE THREAD

**Issue by samsonasik** [elephantly/kahlan-bundle#11]
step to reproduce:

1. install symfony 4 skeleton 
```
composer create-project symfony/skeleton my_project
```

2. install kahlan-bundle with kahlan 4

```
composer require --dev kahlan/kahlan:^4.0 elephantly/kahlan-bundle:^0.9.8
```

3. Try run command:

```
bin/console kahlan:run
```

got error:

```
There are no commands defined in the "kahlan" namespace.
```

It seems the services and commands not automatically registered.

**Comment by Tiriel** [comment]
Hey! Sorry for the long delay, and thanks for the report!

I just checked, it seems there are modifications needed for the commands to load with Symfony 4 indeed.
I'll try some things asap.

**Comment by samsonasik** [comment]
Thank you. Kahlan 4 have different behavior for using Filters, I've created a blog post for sample usage filter with kahlan 4 and symfony 4 : https://samsonasik.wordpress.com/2018/01/03/functional-test-symfony-4-with-kahlan-4/

**Comment by MatthD** [comment]
HI, is it currently possible to use Khalan-bundle for symphony 4 Unit Test ?

**Comment by Th3Mouk** [comment]
I'm starting refactorizing on a fork this bundle, when I'm done I'll do a PR, and you'll be free to merge or not.

**Comment by Th3Mouk** [comment]
After further investigations, Symfony4 no longer need this bundle.

Controller are now services, and with the DI you must use method signature instead of `$this->getContainer()`.

Simple example:
```php
<?php

namespace App\Controller;

use App\Billing\InvoiceSeeker;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\StreamedResponse;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

class BillingController
{
    public function searchInvoice(Request $request, InvoiceSeeker $invoiceSeeker)
    {
        return new JsonResponse($invoiceSeeker->match($request->get('query')));
    }
}

describe('BillingController', function() {

    it('dumb test', function() {
        $request = new \Symfony\Component\HttpFoundation\Request(
            [],
            ['query' => 'yolo@gmail.com']

        );
        $invoiceSeeker = new \App\Billing\InvoiceSeeker();

        $controller = new \App\Controller\BillingController();
        $response = $controller->searchInvoice($request, $invoiceSeeker);

        expect($response)->toBeAnInstanceOf(\Symfony\Component\HttpFoundation\JsonResponse::class);
    });

});
```

**Comment by samsonasik** [comment]
Ok, I am closing it then ;)
