### ISSUE TITLE
Clearer install instructions

### ISSUE THREAD

**Issue by iwnnay** [elephantly/kahlan-bundle#4]
Just a real minor thing. I could update the README if you want with a PR, but it'd be cool if the install instructions had the composer.json part. 

    "elephantly/kahlan-bundle": "0.9.6"

and also that the bundle was in the dev or test only grouping

        if (in_array($this->getEnvironment(), ['dev', 'test'], true)) {
            ...
            $bundles[] = new Elephantly\KahlanBundle\KahlanBundle();
        }

**Comment by Tiriel** [comment]
True! Thanks for the input. Update done!
