### ISSUE TITLE
Support for Symfony Flex

### ISSUE THREAD

**Issue by Brunty** [elephantly/kahlan-bundle#6]
Hey,

I'm looking at getting a contrib recipe for this repo going for Symfony Flex - https://github.com/symfony/recipes-contrib/pull/100

There's a couple of validation issues:

https://symfony.sh/r/github.com/symfony/recipes-contrib/100

```
Package must not depend on symfony/symfony
Type must be "symfony-bundle" as the manifest registers a bundle, "library" detected
```

I'm thinking that the bundle will need to be updated to work with >=3.3 components, as well as potentially re-work what it relies on as things are composed with Flex, rather than just having `symfony/symfony` as a requirement, wanted to put this out there to start a discussion around what could be done (happy to help) to get this working with Flex.

**Comment by PurpleBabar** [comment]
Hey @Brunty, 

Totally agree that the bundle should work with Symfony Flex, @Tiriel any idea on how to make it work ?

**Comment by Tiriel** [comment]
Hey guys. That's indeed a great idea!

I'll rework shortly the composer.json. The bundle doesn't actually need to depend on `symfony/symfony` as far as I can remember, but should depend on `symfony/console` (obviously), `symfony/http` (for request generation/mocking), and `symfony/dependency-injection` (for services testing).

I'll check if it works right this way asap and return to you. If you have any other idea, please feel free to share!

**Comment by Tiriel** [comment]
Addendum: Bundle also depends on `symfony/routing` and on the FrameworkBundle. This last dependency, though, can probably be reworked since it's only for the `ContainerAwareCommand`.

And from what I gather, it probably NEEDS to be reworked, since the FrameworkBundle may not make it to Symfony 4.

**Comment by Brunty** [comment]
Hey, glad to see you're on board with the idea! If there's anything you want me to look into specifically, give me a shout, happy to help with this (and I've got a number of train journeys coming up that should give me time to tinker with some code)

**Comment by Tiriel** [comment]
Well, the main issue here is the dependency on the FrameworkBundle, which causes the dependency on the `symfony/symfony` package.
If you have some thoughts on how to remove/replace this dependency while retaining the functionalities of the `ContainerAwareCommand`, they will be gladly accepted!

On my part, I'll use the small part of leisure time I have left on the problem ;)

**Comment by Brunty** [comment]
Looking at it, the framework bundle is required by the doctrine bundle:

https://github.com/doctrine/DoctrineBundle/blob/1.6.8/composer.json

And that's required by this doctrine recipe: https://github.com/symfony/recipes/blob/master/doctrine/doctrine-bundle/1.6

So I think at the minute, it looks like the `FrameworkBundle` will be sticking around for 4.0 based on those files...?

**Comment by Brunty** [comment]
I'm working on something for this at the minute - had some issues when cloning down, install script didn't work, there looked to be a number of things in the bundle that aren't used anywhere, I'll likely open a PR as a WIP so things can be discussed and worked on.

Also, thoughts on removing the buzz client? It seems like it shouldn't be the responsibility of this bundle to include a client for making requests. Or, if you'd like to provide one do so with something like [HTTPlug](http://httplug.io/) so that the user can determine which client they want to use via an [adapter](http://docs.php-http.org/en/latest/clients.html)

**Comment by Tiriel** [comment]
You're perfectly right, I misread an article by @fabpot where he was explaining the concept of bundle-less applications. It seems in fact the framework-bundle will be the main dependency for mainstream applications, so we can keep this one.

As for buzz, we could think along the lines of making two versions of the bundle, one without any external dependency (including Buzz), and one with everything packed. The main idea was to release a "plug'n play" testing bundle, but I'm open to suggestions!

**Comment by Brunty** [comment]
The idea of a 'plug and play' testing bundle is nice, but would say that a package that includes a client would be installable as a separate thing potentially?

I made a package to use mink in Kahlan too btw - but it's not a bundle, so inspiration could be taken from there (or even use that package in places): https://github.com/brunty/kahlan-mink

**Comment by Tiriel** [comment]
This seems a good idea. I'll check it in depth this evenning. Quick thought though, since I never worked with Mink yet: does it allow testing of non-pages responses? Or to put it more clearly, can you properly test APIs with it?

If not, maybe having multiple distributions of the kahlan-bundle could be an idea, depending on what is one's application purpose: webapp testing, api testing, both, or just the naked bundle if one does want to customize things.

**Comment by Brunty** [comment]
I don't find mink particularly well suited to non-DOM based testing, so a HTTP client would still be best for that IMO.

Could always write a kahlan API testing bundle, use HTTPlug and let people choose their adapter.

I'm going to be moving this package: https://github.com/brunty/api-testcase to HTTPlug sometime soon.

**Comment by Tiriel** [comment]
There's indeed some work possible here.

I think it would be better though to start by merge the changes as they are if they work, so to have a Symfony 4 compatible bundle, and then start working on the rest after.

**Comment by Brunty** [comment]
Sounds good to me, get it working with Flex, then make the additional changes

**Comment by Tiriel** [comment]
Landed in https://github.com/elephantly/kahlan-bundle/commit/6cd2d5b5d99cc3c10138be7404ae2a31041cec99 
Thanks again for your time and patience!
